NL2_TOPICS = {
    #        name, max
    "C1.1": ["การสร้างเสริมสุขภาพ และระบบบริบาลสุขภาพ", 4],
    "C1.2": ["ระบาดวิทยาพื้นฐาน", 3],
    "C1.3": ["ประเมินสุขภาพ และให้คําแนะนําที่เหมาะสมตามช่วงอายุ", 3],
    "C1.4": ["สุขภาพบุคคลและครอบครัว", 2],
    "C1.5": ["ตรวจสุขภาพ คัดกรองโรค และใบรับรองแพทย์", 4],
    "C1.6": ["การตรวจและออกใบรับรองทางนิติเวช", 4],
    "C1.7": ["ชันสูตร วัตถุพยาน และการออกรายงานชันสูตร", 5],
    "C1.8": ["จริยศาสตร์การแพทย์", 5],
    "C2.2": ["โรคกลุ่มอาการ/ภาวะฉุกเฉิน", 50],
    "C2.3.I": ["INFECTIOUS AND PARASITIC DISEASES", 16],
    "C2.3.II": ["NEOPLASM", 7],
    "C2.3.III": ["HEMATOLOGIC & IMMUNE DISEASES", 12],
    "C2.3.IV": ["ENDOCRINE, NUTRITIONAL, AND METABOLIC DISEASES", 14],
    "C2.3.V": ["MENTAL & BEHAVIORAL DISORDERS", 12],
    "C2.3.VI": ["DISORDERS OF THE NERVOUS SYSTEM", 14],
    "C2.3.VII": ["DISORDERS OF THE EYE AND ADNEXA", 7],
    "C2.3.VIII": ["DISORDERS OF THE EAR & MASTOID PROCESS", 7],
    "C2.3.IX": ["DISORDERS OF THE CIRCULATORY SYSTEM", 14],
    "C2.3.X": ["DISORDERS OF THE RESPIRATORY SYSTEM", 14],
    "C2.3.XI": ["DISORDERS OF THE DIGESTIVE SYSTEM", 14],
    "C2.3.XII": ["DISORDERS OF SKIN & SUBCUTANEOUS TISSUE", 7],
    "C2.3.XIII": [
        "DISORDERS OF THE MUSCULOSKELETAL SYSTEM AND CONNECTIVE TISSUE",
        14,
    ],
    "C2.3.XIV": ["DISORDERS OF THE GENITO-URINARY SYSTEM", 15],
    "C2.3.XV": ["PREGNANCY, CHILDBIRTH, AND THE PUERPERIUM", 18],
    "C2.3.XVI": ["CONDITIONS ORIGINATING IN THE PERINATAL PERIOD", 8],
    "C2.3.XVII": [
        "CONGENITAL MALFORMATIONS, DEFORMATIONS AND CHROMOSOMAL ABNORMALITIES",
        5,
    ],
    "C2.3.XVIII": ["INJURY, POISONING AND CONSEQUENCES OF EXTERNAL CAUSES", 12],
    "C2.3.XIX": [" EXTERNAL CAUSES OF MORBIDITY & MORTALITY", 10],
}
